# Generated by Django 5.1.5 on 2025-02-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='http://pluspng.com/img-png/png-user-icon-person-icon-png-people-person-user-icon-2240.png', upload_to='media/account/'),
        ),
    ]
