# Generated by Django 5.1a1 on 2025-02-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_profile_profile_image_profile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='http://pluspng.com/img-png/png-user-icon-person-icon-png-people-person-user-icon-2240.png', upload_to='account/'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
