# Generated by Django 5.1.5 on 2025-02-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customuser_image_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='\x07ccount\\profile.jpg', upload_to='account/'),
        ),
    ]
