# Generated by Django 5.1.5 on 2025-02-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='media/account/profile.jpg', null=True, upload_to='account/'),
        ),
    ]
