# Generated by Django 5.1.5 on 2025-02-01 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0002_postcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='parentComment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialmedia.postcomment'),
        ),
        migrations.AlterModelTable(
            name='postcomment',
            table='PostComment',
        ),
    ]
