# Generated by Django 5.1a1 on 2025-02-26 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership_plan',
            fields=[
                ('plan_id', models.AutoField(null=None, primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=100)),
                ('annual_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_rate', models.FloatField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Membership_plan',
            },
        ),
        migrations.CreateModel(
            name='User_membership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('membership_start_date', models.DateField()),
                ('membership_end_date', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.membership_plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_membership',
            },
        ),
    ]
