# Generated by Django 5.1.5 on 2025-01-30 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('manufacture_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('batch_code', models.CharField(max_length=100, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ProductBatch',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_user_type', models.CharField(choices=[('member', 'Member'), ('non-member', 'Non-member')], default='member', max_length=50)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order_status', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('delivery_charges', models.DecimalField(decimal_places=2, max_digits=5)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_mode', models.CharField(max_length=50)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.user_membership')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.order')),
            ],
            options={
                'db_table': 'Payment',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('product_image', models.ImageField(upload_to='media/products/')),
                ('min_qty', models.ImageField(default=1, upload_to='')),
                ('max_qty', models.IntegerField(default=5)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.category')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('quatity', models.IntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sales', models.DecimalField(decimal_places=2, max_digits=5)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.productbatch')),
            ],
            options={
                'db_table': 'Inventory',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('variant_id', models.AutoField(primary_key=True, serialize=False)),
                ('units', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.brand')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.product')),
            ],
            options={
                'db_table': 'ProductVariant',
            },
        ),
        migrations.AddField(
            model_name='productbatch',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.productvariant'),
        ),
        migrations.CreateModel(
            name='Order_Item',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.order')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.productbatch')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.productvariant')),
            ],
            options={
                'db_table': 'OrderItem',
            },
        ),
    ]
