# Generated by Django 5.1.5 on 2025-02-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pincode',
            old_name='pincode',
            new_name='area_pincode',
        ),
    ]
