# Generated by Django 5.1a1 on 2025-02-26 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ecommerce', '0001_initial'),
        ('membership', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.cart'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.city'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order_item',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.order'),
        ),
        migrations.AddField(
            model_name='payment',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.user_membership'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.order'),
        ),
        migrations.AddField(
            model_name='pincode',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.city'),
        ),
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.pincode'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.category'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.product'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.product'),
        ),
        migrations.AddField(
            model_name='order_item',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.productbatch'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.productbatch'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.productbatch'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.brand'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.product'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.productvariant'),
        ),
        migrations.AddField(
            model_name='order_item',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.productvariant'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.productvariant'),
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.product'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='product_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.productbatch'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.productvariant'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.wishlist'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product_batch', 'product_variant')},
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('wishlist', 'product_batch', 'product_variant')},
        ),
    ]
