# Generated by Django 5.1.5 on 2025-03-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0004_rename_transaction_id_payment_razor_pay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='razor_pay_order_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razor_pay_payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razor_pay_payment_signature',
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
