# Generated by Django 5.1a1 on 2025-01-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0004_deliveryzone_payment_create_at_alter_brand_create_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='min_qty',
            field=models.IntegerField(default=1),
        ),
    ]
