# Generated by Django 5.1.5 on 2025-02-01 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0005_alter_product_min_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='sales',
            new_name='sales_price',
        ),
    ]
