# Generated by Django 5.1.5 on 2025-02-09 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0005_alter_review_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
