# Generated by Django 5.1a1 on 2025-02-01 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0006_rename_sales_inventory_sales_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.product'),
            preserve_default=False,
        ),
    ]
