# Generated by Django 5.1a1 on 2025-02-12 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0009_cartitem_price_cartitem_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='total_price',
        ),
    ]
