# Generated by Django 5.1.5 on 2025-02-02 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0010_alter_payment_membership_alter_payment_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Wishlist',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cart_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.cart')),
                ('product_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.productbatch')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.productvariant')),
            ],
            options={
                'db_table': 'CartItem',
                'unique_together': {('cart', 'product_batch', 'product_variant')},
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.productbatch')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.productvariant')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.wishlist')),
            ],
            options={
                'db_table': 'WishlistItem',
                'unique_together': {('wishlist', 'product_batch', 'product_variant')},
            },
        ),
    ]
