# Generated by Django 5.1a1 on 2025-02-14 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0010_remove_cartitem_price_remove_cartitem_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
