# Generated by Django 5.1a1 on 2025-02-03 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0011_cart_wishlist_cartitem_wishlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'City',
            },
        ),
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('pincode_id', models.AutoField(primary_key=True, serialize=False)),
                ('pincode', models.CharField(max_length=10, unique=True)),
                ('delivery_charges', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.city')),
            ],
            options={
                'db_table': 'Pincode',
            },
        ),
        migrations.DeleteModel(
            name='DeliveryZone',
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.city'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pincode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.pincode'),
        ),
    ]
