# Generated by Django 5.1a1 on 2025-02-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0012_city_pincode_delete_deliveryzone_alter_order_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default=1, upload_to='media/products/'),
            preserve_default=False,
        ),
    ]
