# Generated by Django 5.1.5 on 2025-02-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0012_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
