# Generated by Django 5.1a1 on 2025-02-03 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0014_rename_category_image_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='category_image',
        ),
    ]
